### ISSUE TITLE
Syntax for list comprehensions

### ISSUE THREAD

**Issue by chavacava** [JasonSteving99/claro-lang#52]
Hi @JasonSteving99, awesome work!

I'm reading the reference guide carefully and I find Claro a nice and pleasant language.

I love the pipe operator (that I first met with Elm) and, as you explain [here](https://docs.clarolang.com/control_flow/pipes/pipes.generated_docs.html?highlight=pipe#textually-linear-data-flow) it allows program text and data to flow in the same direction (thus its easier to read than the pipes-free version)
(BTW, I found the `^` back-reference operator very clean and clear)

That property of program text and data flowing in the same direction is somewhat broken in the case of list comprehensions because identifiers are used before they are defined. For example, in 

```
[strings::repeated("*", x) | x in [1, 3, 99, 2, 1] where x <= 10]
```

`x` is referenced (in `strings::repeated("*", x)`) before its _definition_ (as `x in [1, 3, 99, 2, 1] where x <= 10`)

In short and simple list comprehensions, as the above one, the syntax might not be an obstacle for understanding but in longer comprehensions understanding is hindered. For example, in the following code:
  
https://github.com/JasonSteving99/claro-lang/blob/d7297f79d46e1c083fd3f2dbe77c5a10bb23007d/examples/claro_programs/advent_of_code_2023/day_01/part1.claro#L2-L10

The reader needs to go until line 9 to find the definition of `line` and then go back to line 7 where `line` is used to define `x` that is first referenced at line 6.

I know the roots of the syntax for list comprehensions is the [set builder notation](https://www.wikiwand.com/en/Set-builder_notation) but IMO that syntax is OK for simple cases (as is the case of all the examples provided in the description of the notation) but for more complex cases the syntax that reverts the order use-def into def-use is more clear. There are languages, like Scala, with a syntax like that.

I think something like
```
files::readOrPanic(resources::Input)
  |> strings::split(^, "\n")
  |> [ line in ^ ->
      [ x in strings::splitChars(line) where ints::parseInt(strings::fromChar(x)) instanceof int ->
        ints::parseInt(strings::fromChar(x))
      ]
     ]
```
reads better than
https://github.com/JasonSteving99/claro-lang/blob/d7297f79d46e1c083fd3f2dbe77c5a10bb23007d/examples/claro_programs/advent_of_code_2023/day_01/part1.claro#L2-L10

What do you think?

**Comment by JasonSteving99** [comment]
Hey @chavacava thank you for taking an interest in Claro! And I really appreciate the thoughtful suggestion. So, I actually largely agree with you here that Claro's set builder notation based comprehensions sort of invalidate Claro's other stated goal of code reading in a single direction. I've mulled over making a change like you suggested before actually. 

At the moment, there are two things that are making me resist changing the syntax:
1. This ordering is probably fairly familiar to many people as it's the way Python does things (not that they're identical).
2. Given how tightly integrated Claro is with Bazel, the fact that Bazel `BUILD` and `.bzl` files are written in a subset of Python (Starlark) that expose comprehension syntax ([e.g.](https://docs.clarolang.com/metaprogramming/code_reuse/reusing_module_apis/reusing_module_apis.generated_docs.html#fig-8)) makes me think it's valuable to try to reduce the cognitive friction between the two languages on this point. (To be fair, you may rightly argue that since Claro's comprehensions aren't _identical_ to Python comprehensions, the benefit here is questionable - very subjective.)


Whether those above points actually justify the syntax is very subjective, so I'd love to hear your thoughts.

**Comment by JasonSteving99** [comment]
Well, I think it's worth keeping in mind that the entire premise of this conversation is subjective. Even the idea that code "should" read in one direction isn't an objective truth. I prefer that approach but wouldn't sacrifice other things I value to achieve that exhaustively. So ya, tradeoffs everywhere. 

Python itself doesn't really hold any significant weight for me aside from the Bazel connection. I'm not sure that Claro particularly targets any particular language community. It's a new language, and maybe will acquire a small new community at some point in time and if so we'll work together to decide on Claro norms. The one thing to say for sure is that Claro is not targeting "systems" programmers - Claro is for folks that are happy with garbage collection and the like.
